### ISSUE TITLE
爬虫运行出错

### ISSUE THREAD

**Issue by lylsq** [Ddosser/wooyunspider#3]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 72, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 97, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 71, in **init**
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/media.py", line 33, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/images.py", line 61, in from_settings
    return cls(store_uri, settings=settings)
TypeError: **init**() got an unexpected keyword argument 'settings'

请教一下哪里出了问题?

**Comment by Ddosser** [comment]
抱歉，很久没有用了。上面的错误应该是setting.py里的一些路径不存在导致，因为设置时是根据我自己路径设置的。

**Comment by Bajie-cigarette** [comment]
不知道这位仁兄的问题解决了没有，我也是类似的错误，而且我检查了setting.py，里面的路径都是存在的，这个错误已经耽搁我很久了。。。。

**Comment by Ddosser** [comment]
这位大哥，我这个爬虫是爬了存在mongodb里的，所以需要安装mongodb，且settings.py里的密码得和相应的数据库密码一样。
